package com.tharun.routes;
// Generated Feb 4, 2013 5:14:58 PM by Hibernate Tools 3.2.1.GA



/**
 * RouteDescriptions generated by hbm2java
 */
public class RouteDescriptions  implements java.io.Serializable {


     private String routeIdUrl;
     private String routeDescription;

    public RouteDescriptions() {
    }

    public RouteDescriptions(String routeIdUrl, String routeDescription) {
       this.routeIdUrl = routeIdUrl;
       this.routeDescription = routeDescription;
    }
   
    public String getRouteIdUrl() {
        return this.routeIdUrl;
    }
    
    public void setRouteIdUrl(String routeIdUrl) {
        this.routeIdUrl = routeIdUrl;
    }
    public String getRouteDescription() {
        return this.routeDescription;
    }
    
    public void setRouteDescription(String routeDescription) {
        this.routeDescription = routeDescription;
    }




}


