package com.tharun.routes;
// Generated Feb 4, 2013 6:19:40 PM by Hibernate Tools 3.2.1.GA



/**
 * RouteLandmarks generated by hbm2java
 */
public class RouteLandmarks  implements java.io.Serializable {


     private Integer id;
     private String landmark;
     private String sentenseIds;

    public RouteLandmarks() {
    }

    public RouteLandmarks(String landmark, String sentenseIds) {
       this.landmark = landmark;
       this.sentenseIds = sentenseIds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLandmark() {
        return this.landmark;
    }
    
    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }
    public String getSentenseIds() {
        return this.sentenseIds;
    }
    
    public void setSentenseIds(String sentenseIds) {
        this.sentenseIds = sentenseIds;
    }




}


